language: rust

cache:
  cargo: true

script:
  - cargo clean
  - cargo build
  - cargo test

rust:
  - stable
  - beta
  - nightly

matrix:
  fast_finish: true

notifications:
  email: false

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi