language: rust

cache:
  cargo: true

script:
  - cargo clean
  - cargo build
  - cargo test

rust:
  - stable
  - beta
  - nightly

matrix:
  fast_finish: true

notifications:
  email: false

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
  fi

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
